### ISSUE TITLE
not launching

### ISSUE THREAD

**Issue by broski12312** [WitheredKnights/badlionCrack#2]
![image](https://github.com/WitheredKnights/badlionCrack/assets/158988290/d80f94ae-f621-4cdf-b814-09add8119e87)

**Comment by broski12312** [comment]
im on pop os btw

**Comment by PrimeTDMomega** [comment]
![image](https://github.com/WitheredKnights/badlionCrack/assets/105910256/aee3415a-05b1-41f3-809b-6ea77ceee721)
You made a mistake in this part, ppl often skip it after reading download section. If it launched and shows that window means you have done the Installation correctly just usage is wrong. Try following the Usage section again carefully.

Even if it ends up working still join our [discord server](https://discord.gg/4mjzMGv7Xe) so I can confirm that was the problem. If problem persists just ping any of the staff in the #support channel.
